##################################################
# Edited by Tran Tuan Anh
# github : anhconstant 
##################################################
# target
TARGET = gpio

# source
######################################
# C sources
C_SOURCES =  
C_SOURCES += ${DIR}/Src/main.c 
C_SOURCES += ${DIR}/Src/stm32f10x_it.c 
C_SOURCES += ${DIR}/Src/system_stm32f10x.c  
# C_SOURCES += ${DIR}/Drivers/STM32F10x_StdPeriph_Driver/src/misc.c 
# C_SOURCES += ${DIR}/Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_adc.c 
# C_SOURCES += ${DIR}/Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_bkp.c 
# C_SOURCES += ${DIR}/Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_can.c 
# C_SOURCES += ${DIR}/Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_cec.c 
# C_SOURCES += ${DIR}/Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_crc.c 
# C_SOURCES += ${DIR}/Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_dac.c 
# C_SOURCES += ${DIR}/Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_dbgmcu.c 
# C_SOURCES += ${DIR}/Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_dma.c 
# C_SOURCES += ${DIR}/Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_exti.c 
# C_SOURCES += ${DIR}/Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_flash.c 
# C_SOURCES += ${DIR}/Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_fsmc.c 
C_SOURCES += ${DIR}/Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_gpio.c 
# C_SOURCES += ${DIR}/Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_i2c.c 
# C_SOURCES += ${DIR}/Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_iwdg.c 
# C_SOURCES += ${DIR}/Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_pwr.c 
C_SOURCES += ${DIR}/Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_rcc.c 
# C_SOURCES += ${DIR}/Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_rtc.c 
# C_SOURCES += ${DIR}/Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_sdio.c 
# C_SOURCES += ${DIR}/Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_spi.c 
# C_SOURCES += ${DIR}/Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_tim.c 
# C_SOURCES += ${DIR}/Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_usart.c 
# C_SOURCES += ${DIR}/Drivers/STM32F10x_StdPeriph_Driver/src/stm32f10x_wwdg.c 


# ASM sources
include ../Makefile
